[versions]
kotlin = "2.2.20"
detekt = "1.23.8"
cyclonedx-plugin = "3.0.0"
ksp = "2.2.20-2.0.4"
micronaut-plugin = "4.5.5"
micronaut = "4.9.4"
openapi-generator = "7.16.0"
shadow = "8.3.9"
mockito-kotlin = "6.1.0"
jsoup = "1.16.1"
flying-saucer-pdf = "9.11.3"
commons-io = "2.14.0"
jackson-csv = "2.17.2"
okhttp = "5.2.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
micronaut-library = { id = "io.micronaut.library", version.ref = "micronaut-plugin" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-plugin" }
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronaut-plugin" }
micronaut-test-resources = { id = "io.micronaut.test-resources", version.ref = "micronaut-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
cyclonedx-bom = { id = "org.cyclonedx.bom", version.ref = "cyclonedx-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }

[libraries]
#micronaut-bom is added automatically by the micronaut plugin, here we just declare it so dependabot can manage the version
micronaut-bom = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
flying-saucer-pdf = { module = "org.xhtmlrenderer:flying-saucer-pdf", version.ref = "flying-saucer-pdf" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
jackson-dataformat-csv = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-csv", version.ref = "jackson-csv" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
